"""Add profile photo columns to users table

Revision ID: 0b8b01cb6f4d
Revises: 44b6d6866050
Create Date: 2026-01-27 17:21:59.099083+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8b01cb6f4d'
down_revision = '44b6d6866050'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('photo_mime_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_mime_type')
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###